// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_favar_cpp
NumericVector simulate_favar_cpp(NumericVector constant, NumericVector transition, NumericMatrix residuals, NumericMatrix last_states, int horizon, int n_scenarios);
RcppExport SEXP _scenario2risk_simulate_favar_cpp(SEXP constantSEXP, SEXP transitionSEXP, SEXP residualsSEXP, SEXP last_statesSEXP, SEXP horizonSEXP, SEXP n_scenariosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type transition(transitionSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type last_states(last_statesSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< int >::type n_scenarios(n_scenariosSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_favar_cpp(constant, transition, residuals, last_states, horizon, n_scenarios));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scenario2risk_simulate_favar_cpp", (DL_FUNC) &_scenario2risk_simulate_favar_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_scenario2risk(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
