# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_favar_cpp <- function(constant, transition, residuals, last_states, horizon, n_scenarios) {
    .Call(`_scenario2risk_simulate_favar_cpp`, constant, transition, residuals, last_states, horizon, n_scenarios)
}

